//
// Created by Nagy Gábor on 2019. 02. 05..
//

#ifndef GREEN_FOX_INHERITANCE_EXCERCISE_STUDENT_H
#define GREEN_FOX_INHERITANCE_EXCERCISE_STUDENT_H


class Student {


};


#endif //GREEN_FOX_INHERITANCE_EXCERCISE_STUDENT_H
